# .github/workflows/app1-deploy.yml
name: Employer Deployment

on:
  push:
    branches:
      - main
    paths:
      - "apps/employer/**"
      - "packages/**" # Include shared packages
  pull_request:
    branches:
      - main
    paths:
      - "apps/employer/**"
      - "packages/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install Dependencies
        run: npm install
      - name: Install TurboRepo
        run: npm install turbo --global

      - name: Build employer
        run: turbo build --filter=employer

      - name: Deploy employer
        run: echo "Add your deployment steps here"
        # Add your specific deployment steps
