name: Deploy Turbo Apps

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.0" # Use your node version here

      - name: Install dependencies
        run: npm install

      - name: Install TurboRepo
        run: npm install turbo --global

      # Detect changes in packages and apps
      - name: Detect changed packages
        id: changes
        run: |
          turbo build --filter=[origin/main]
