name: Deploy Turbo Apps

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.13.0" # Updated to a valid Node.js version

      - name: Debug Git Info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "Current SHA: ${{ github.sha }}"
          git rev-parse HEAD

      - name: Install dependencies
        run: npm install

      - name: Install TurboRepo
        run: npm install turbo --global

      - name: Detect changed packages
        id: changes
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_SHA=${{ github.event.pull_request.base.sha }}
            # Fallback if base SHA is empty
            if [ -z "$BASE_SHA" ]; then
              BASE_SHA=$(git rev-parse HEAD^1)
            fi
            turbo build --filter=[$BASE_SHA]
          else
            # For push events, use the previous commit
            turbo build --filter=[HEAD^1]
          fi
